# Generated by Django 5.2 on 2025-04-10 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='Scenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_key', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envapp.characters')),
            ],
            options={
                'db_table': 'Scenes',
                'unique_together': {('character', 'scene_key')},
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('feedback', models.TextField()),
                ('emotion', models.CharField(max_length=50)),
                ('correct', models.BooleanField()),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envapp.scenes')),
            ],
            options={
                'db_table': 'Options',
            },
        ),
    ]
