# Generated by Django 5.2 on 2025-05-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('full_text', models.TextField(blank=True)),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField()),
                ('trimester', models.CharField(choices=[('1', 'Trimester 1'), ('2', 'Trimester 2'), ('3', 'Trimester 3')], max_length=20)),
                ('age_group', models.CharField(max_length=50)),
                ('heat_sensitive', models.BooleanField(default=False)),
                ('pollution_sensitive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'InfoCard',
            },
        ),
    ]
